server.port:  8080

solon.app:
  group: demo
  name: demoapp

# 数据源配置示例
solon.dataSources:
  demo!:
    class: "com.zaxxer.hikari.HikariDataSource"
    jdbcUrl: "jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;IGNORECASE=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE"
    driverClassName: "org.h2.Driver"

# 以下为默认值，可以都不加，或者想改哪行加哪行(支持"云端配置服务"进行配置，支持写到"云端日志服务")
solon.logging.appender:
  console:
    level: TRACE
  file:
    name: "logs/${solon.app.name}"
    level: INFO
    maxFileSize: "10 MB"
    maxHistory: "7"
    enable: false
  cloud:
    level: INFO

# 记录器级别的配置示例
solon.logging.logger:
  "root":  #默认记录器配置
    level: TRACE
  "com.zaxxer.hikari.*":
    level: INFO